# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Cache Iverilog
        id: cache-iverilog
        uses: actions/cache@v2
        with:
          path: /usr/local/bin/iverilog
          key: ${{ runner.os }}-iverilog
          
      - name: Install iverilog
        if: steps.cache-iverilog.outputs.cache-hit != 'true'
        run: |
          wget ftp://ftp.icarus.com/pub/eda/verilog/v11/verilog-11.0.tar.gz
          sudo tar -zxvf verilog-11.0.tar.gz   
          cd verilog-11.0
          sudo ./configure  
          sudo make
          sudo make install
          iverilog -V 
          echo $(which iverilog)

      - name: Install verilator
        run: |
          echo Installing Verilator
          sudo apt-get install verilator  
          
      - name: Configure
        run: |
          sudo mkdir build && cd build
          sudo ../configure 
          sudo make
          
      - name: Test lab1
        run: |
          echo Testing lab1
          cd build
          sudo make lab1-imul-check
          sudo make lab1-imul-IntMulFL-test   && ./lab1-imul-IntMulFL-test
          sudo make lab1-imul-IntMulBase-test && ./lab1-imul-IntMulBase-test 
          sudo make lab1-imul-check           && ./lab1-imul-IntMulAlt-test
              
      - name: Test All
        run: |
          echo Testing all subprojects
          cd build
          sudo make check
            
      - name: Archive build artifact        
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: |
             build
             
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          event-type: test-pass
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'         

